# Generated by Django 4.2.26 on 2025-11-11 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('elevation_ft', models.PositiveIntegerField(blank=True, null=True)),
                ('prominence_ft', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=32)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('external_source', models.CharField(blank=True, max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=120)),
                ('external_country', models.CharField(blank=True, max_length=120)),
                ('external_range', models.CharField(blank=True, max_length=120)),
                ('external_elevation_m', models.PositiveIntegerField(blank=True, null=True)),
                ('external_prominence_m', models.PositiveIntegerField(blank=True, null=True)),
                ('external_retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('external_payload', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('distance_mi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('vert_gain_ft', models.PositiveIntegerField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=32)),
                ('season', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('peak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='peak_planner.peak')),
            ],
            options={
                'ordering': ['peak__name', 'name'],
                'unique_together': {('peak', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TripPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('team_size', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('ready', 'Ready'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='planned', max_length=20)),
                ('objectives', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='peak_planner.route')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peak_trip_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AscentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome', models.CharField(blank=True, max_length=20)),
                ('time_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_at', models.DateField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ascents', to='peak_planner.tripplan')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
